# Generated by Django 3.2.7 on 2021-09-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20210928_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='Timestamp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='base',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
