# Generated by Django 3.2.7 on 2021-09-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_alter_base_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
