# Generated by Django 3.2.7 on 2021-09-28 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0005_alter_base_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
